export const cards = [
   {
     "id": 1,
     "image": "../../assets/images/cards-img/hookan.png",
     "price": 400,
    "description": "Voluptate et sed tempora qui quisquam",
   },
   {
     "id": 2,
     "image": "../../assets/images/cards-img/dress.png",
     "price": 400,
     "description": "Voluptate et sed tempora qui quisquam",
   },
   {
     "id": 3,
     "image": "../../assets/images/cards-img/faces.png",
     "price": 400,
     "description": "Voluptate et sed tempora qui quisquam",
   },
   {
     "id": 4,
     "image": "../../assets/images/cards-img/smile.png",
     "price": 400,
     "description": "Voluptate et sed tempora qui quisquam",
   },
   {
     "id": 5,
     "image": "../../assets/images/cards-img/movies.png",
     "price": 400,
     "description": "Voluptate et sed tempora qui quisquam",
   },
   {
      "id": 6,
      "image": "../../assets/images/cards-img/hookan.png",
      "price": 400,
     "description": "Voluptate et sed tempora qui quisquam",
    },
    {
      "id": 7,
      "image": "../../assets/images/cards-img/dress.png",
      "price": 400,
      "description": "Voluptate et sed tempora qui quisquam",
    },
    {
      "id": 8,
      "image": "../../assets/images/cards-img/faces.png",
      "price": 400,
      "description": "Voluptate et sed tempora qui quisquam",
    },
    {
      "id": 9,
      "image": "../../assets/images/cards-img/smile.png",
      "price": 400,
      "description": "Voluptate et sed tempora qui quisquam",
    },
    {
      "id": 10,
      "image": "../../assets/images/cards-img/movies.png",
      "price": 400,
      "description": "Voluptate et sed tempora qui quisquam",
    },
    {
      "id": 11,
      "image": "../../assets/images/cards-img/hookan.png",
      "price": 400,
      "description": "Voluptate et sed tempora qui quisquam",
    },
    {
      "id": 12,
      "image": "../../assets/images/cards-img/dress.png",
      "price": 400,
      "description": "Voluptate et sed tempora qui quisquam",
    },
    {
      "id": 13,
      "image": "../../assets/images/cards-img/faces.png",
      "price": 400,
      "description": "Voluptate et sed tempora qui quisquam",
    },
    {
      "id": 14,
      "image": "../../assets/images/cards-img/smile.png",
      "price": 400,
      "description": "Voluptate et sed tempora qui quisquam",
    },
    {
      "id": 15,
      "image": "../../assets/images/cards-img/movies.png",
      "price": 400,
      "description": "Voluptate et sed tempora qui quisquam",
    },
    {
      "id": 16,
      "image": "../../assets/images/cards-img/hookan.png",
      "price": 400,
      "description": "Voluptate et sed tempora qui quisquam",
    },
    {
      "id": 17,
      "image": "../../assets/images/cards-img/dress.png",
      "price": 400,
      "description": "Voluptate et sed tempora qui quisquam",
    },
    {
      "id": 18,
      "image": "../../assets/images/cards-img/faces.png",
      "price": 400,
      "description": "Voluptate et sed tempora qui quisquam",
    },
    {
      "id": 19,
      "image": "../../assets/images/cards-img/smile.png",
      "price": 400,
      "description": "Voluptate et sed tempora qui quisquam",
    },
    {
      "id": 20,
      "image": "../../assets/images/cards-img/movies.png",
      "price": 400,
      "description": "Voluptate et sed tempora qui quisquam",
    },
    {
      "id": 21,
      "image": "../../assets/images/cards-img/hookan.png",
      "price": 400,
      "description": "Voluptate et sed tempora qui quisquam",
    },
    {
      "id": 22,
      "image": "../../assets/images/cards-img/dress.png",
      "price": 400,
      "description": "Voluptate et sed tempora qui quisquam",
    },
    {
      "id": 23,
      "image": "../../assets/images/cards-img/faces.png",
      "price": 400,
      "description": "Voluptate et sed tempora qui quisquam",
    },
    {
      "id": 24,
      "image": "../../assets/images/cards-img/smile.png",
      "price": 400,
      "description": "Voluptate et sed tempora qui quisquam",
    },
    {
      "id": 25,
      "image": "../../assets/images/cards-img/movies.png",
      "price": 400,
      "description": "Voluptate et sed tempora qui quisquam",
    }
]